import { Product } from './types';

export const SITE_CONFIG = {
  name: 'Gurukripa Traders',
  tagline: 'Vardaan & Shri Kesari Poojan Oils',
  description: 'Canons of Scriptural Purity. Authentic Cold-Pressed Sesame Oils, Consecrated Deep Dravya, and Sacred Hawan Samagri for Temples & Shrines.',
  contactPhone: '+91 98765 43210',
  contactEmail: 'orders@gurukripatraders.com',
  address: 'Main Temple Road, Sacred Industrial Hub, Mathura, UP - 281001',
  bannerAnnouncement: '⚡ Free Shipping on all orders above ₹999 • Compliment Temple Blessed Silver Coin with Orders Above ₹2,999 ⚡',
};

export const PRODUCTS: Product[] = [
  {
    id: 'vardaan-til-tail',
    name: 'Vardaan Til Tail (वरदान दीपक जलाने का तेल)',
    hindiTitle: '100% शुद्ध तिल का तेल (दीपक हेतु)',
    category: 'Vardaan Oil Series',
    price: 249,
    originalPrice: 380,
    rating: 4.9,
    reviewsCount: 1420,
    badge: 'BESTSELLER • 36H AKHAND FLAME',
    image: '/images/vardaan-bottles.png',
    description: 'Canons of Scriptural Purity: 100% cold-pressed sesame oil infused with natural Bhimseni camphor notes. Formulated specifically to guarantee a soot-free, non-blackening 36-hour continuous Akhand flame for home temples.',
    features: [
      'Zero Carbon Soot Build-up',
      '36-Hour Continuous Akhand Deepam Flame',
      'Cold-Pressed First Extraction Sesame Base',
      'Infused with Sacred Bhimseni Camphor Notes',
    ],
    variants: [
      { id: 'vtt-1l', name: '1 Litre Bottle', unit: '1L', price: 249, originalPrice: 380 },
      { id: 'vtt-5l', name: '5 Litre Temple Can', unit: '5L', price: 1199, originalPrice: 1650 },
      { id: 'vtt-box', name: 'Case of 12 (1L Bottles)', unit: '12L', price: 2799, originalPrice: 3999 },
    ],
    sankalpOption: true,
  },
  {
    id: 'shri-kesari-dravya-jar',
    name: 'Shri Kesari Yellow Dravya Jars (श्री केसरी वंदना दीप द्रव्य)',
    hindiTitle: 'पीला जार - वंदना दीप द्रव्य',
    category: 'Kesari Deep Dravya',
    price: 299,
    originalPrice: 420,
    rating: 4.95,
    reviewsCount: 980,
    badge: 'TEMPLE GRADE • AIRTIGHT JAR',
    image: '/images/kesari-jars.png',
    description: 'Consecrated Deep Dravya stored in airtight yellow jars. Emits a warm golden flame with natural aromatic essence, ideal for daily Aarti and Mahadeep worship.',
    features: [
      'Consecrated Yellow Jar Packaging',
      'Radiant Golden Flame & Zero Smoke',
      'Enriched with Sacred Vedic Herbal Extracts',
      'UV-Protected Airtight Preservation',
    ],
    variants: [
      { id: 'skd-500g', name: '500g Airtight Jar', unit: '500g', price: 299, originalPrice: 420 },
      { id: 'skd-1kg', name: '1kg Jumbo Jar', unit: '1kg', price: 549, originalPrice: 799 },
    ],
    sankalpOption: true,
  },
  {
    id: 'shri-kesari-plus-box',
    name: 'Shri Kesari Plus Gift Boxes (श्री केसरी प्लस दीप)',
    hindiTitle: 'बॉक्स पैक - श्री केसरी प्लस',
    category: 'Curated Ritual Boxes',
    price: 349,
    originalPrice: 499,
    rating: 4.88,
    reviewsCount: 650,
    badge: 'ROYAL GIFT EDITION',
    image: '/images/kesari-boxes.png',
    description: 'Royal festival box edition containing consecrated Kesari Plus Deep Dravya. Excellent for Diwali gifting, Gruha Pravesh, and corporate temple consignments.',
    features: [
      'Royal Embossed Festival Gift Packaging',
      'Includes Brass Wicks & Consecrated Dravya',
      'Scriptural Purity Certificate Included',
      'Ideal for Deepavali & Gruha Pravesh Gifting',
    ],
    variants: [
      { id: 'skp-single', name: 'Single Royal Box (500g)', unit: '500g', price: 349, originalPrice: 499 },
      { id: 'skp-pair', name: 'Twin Festive Pack (2x 500g)', unit: '1kg', price: 649, originalPrice: 950 },
    ],
    sankalpOption: true,
  },
  {
    id: 'kashmiri-saffron-ghee',
    name: 'Kashmiri Saffron & A2 Gir Cow Ghee (केसर एवं वैदिक बिलोना घृत)',
    hindiTitle: 'कश्मीरी मोंगरा केसर एवं बिलोना घृत',
    category: 'Purity Guarantee Essentials',
    price: 899,
    originalPrice: 1250,
    rating: 5.0,
    reviewsCount: 1120,
    badge: 'GRADE A1 KASHMIRI MONGRA',
    image: '/images/kesari-jars.png',
    description: 'Handpicked Grade A1 Kashmiri Saffron filaments paired with traditional Bilona method A2 Gir Cow Vedic Ghee for Abhishek, Yajna, and Panchamrit rituals.',
    features: [
      '100% Pure Grade A1 Kashmiri Mongra Saffron',
      'Vedic Bilona Method A2 Gir Cow Ghee',
      'Lab Certified Zero Chemical Adulteration',
      'Aromatic Golden Flame & Holy Fragrance',
    ],
    variants: [
      { id: 'ksg-250g', name: '250g Glass Jar Ghee + 1g Saffron', unit: '250g', price: 899, originalPrice: 1250 },
      { id: 'ksg-500g', name: '500g Glass Jar Ghee + 2g Saffron', unit: '500g', price: 1699, originalPrice: 2400 },
    ],
    sankalpOption: true,
  },
  {
    id: 'curated-poojan-kit',
    name: 'Curated Shahi Poojan Trunk (शाही पूजन सामग्री ट्रंक)',
    hindiTitle: '32 आवश्यक पूजन सामग्री किट',
    category: 'Curated Ritual Boxes',
    price: 1499,
    originalPrice: 2199,
    rating: 4.97,
    reviewsCount: 810,
    badge: 'COMPLETE 32 ITEM TRUNK',
    image: '/images/kesari-boxes.png',
    description: 'Cedarwood trunk filled with 32 essential consecrated samagri items for Hawan, Lakshmi Pujan, and milestone Mahayagnas prepared by Vedic Acharyas.',
    features: [
      '32 Consecrated Samagri Items Included',
      'Handcrafted Cedarwood Storage Trunk',
      'Prepared Under Guidance of Mathura Acharyas',
      'Complete Yajna & Lakshmi Puja Ready',
    ],
    variants: [
      { id: 'cpk-standard', name: 'Standard Shahi Kit (32 Items)', unit: '32 Items', price: 1499, originalPrice: 2199 },
      { id: 'cpk-grand', name: 'Grand Mahayajna Trunk (48 Items)', unit: '48 Items', price: 2799, originalPrice: 3999 },
    ],
    sankalpOption: true,
  },
];

export const PURITY_STANDARDS = [
  {
    title: '100% First Cold-Pressed Sesame Base',
    description: 'Extracted directly from selected black & yellow sesame seeds using traditional wooden ghanis without solvent chemicals or thermal oxidation.',
    standard: 'IS 542:2014 & Scriptural Canons',
    iconName: 'Droplets',
  },
  {
    title: 'Zero Carbon Soot & Non-Blackening Flame',
    description: 'Infused with pure Bhimseni camphor notes that maintain complete combustion, ensuring zero soot marks on temple marble and idols.',
    standard: 'HPLC Tested 99.8% Soot-Free',
    iconName: 'Flame',
  },
  {
    title: 'Airtight UV-Protected Consecrated Jars',
    description: 'Packaged in heavy-gauge leakproof containers under hygienic, consecrated conditions with Gotra Sankalp readiness.',
    standard: 'ISO 22000 & Temple Certified',
    iconName: 'ShieldCheck',
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Mahant Raghav Das Ji',
    author: 'Mahant Raghav Das Ji',
    role: 'Head Priest, Shri Bankey Bihari Temple Complex',
    location: 'Mathura, UP',
    rating: 5,
    comment: 'We have been using Gurukripa Traders Vardaan Til Tail for all our daily Aarti lamps. The flame burns bright, clear, and without a speck of black soot on the temple marble. Truly divine purity.',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 't2',
    name: 'Smt. Sunita Agarwal',
    author: 'Smt. Sunita Agarwal',
    role: 'Devotee, New Delhi',
    location: 'New Delhi',
    rating: 5,
    comment: 'The Shri Kesari Yellow Jars are remarkable! The oil has a soothing sacred scent and burns for hours during Navratri Akhand Jyoti. Packing was airtight and leaked zero drop.',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 't3',
    name: 'Pundit Vishnu Dev Shastri',
    author: 'Pundit Vishnu Dev Shastri',
    role: 'Vedic Ritual Scholar, Varanasi',
    location: 'Varanasi, UP',
    rating: 5,
    comment: 'Their A2 Ghee and Kashmiri Saffron meet every scriptural standard for Mahayagna Abhishek. Highly recommend to all temple trusts and devout families.',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
  },
];
