import { Product } from './types';

export const SITE_CONFIG = {
  name: 'Gurukripa Traders',
  tagline: 'Vardaan & Shri Kesari Poojan Oils',
  description: 'Canons of Scriptural Purity. Authentic Cold-Pressed Sesame Oils, Consecrated Deep Dravya, and Sacred Hawan Samagri for Temples & Shrines.',
  contactPhone: '+91 98765 43210',
  contactEmail: 'contact@gurukripatraders.com',
  address: 'Hanuman Ganj Road, Near Hanuman Mandir, Jumerati Market, Bhopal, MP - 462001',
  openingHours: 'Mon - Sat: 10:30 AM - 8:30 PM (Sunday Closed)',
  rating: '4.4 ★ (Verified Merchant)',
  bannerAnnouncement: '⚡ Free Shipping on all orders above ₹999 • Compliment Temple Blessed Silver Coin with Orders Above ₹2,999 ⚡',
};

export const PRODUCTS: Product[] = [
  {
    id: 'vardaan-til-tail',
    name: 'Vardaan Oil (वरदान दीपक जलाने का तेल)',
    hindiTitle: '100% शुद्ध तिल का तेल (दीपक हेतु)',
    category: 'Vardaan Oil Series',
    price: 249,
    originalPrice: 380,
    rating: 4.9,
    reviewsCount: 1420,
    // badge: 'BESTSELLER • 36H AKHAND FLAME',
    image: '/images/vardaan-bottles.png',
    description: 'Canons of Scriptural Purity: 100% cold-pressed sesame oil infused with natural Bhimseni camphor notes. Formulated specifically to guarantee a soot-free, non-blackening 36-hour continuous Akhand flame for home temples.',
    features: [
      'Zero Carbon Soot Build-up',
      '36-Hour Continuous Akhand Deepam Flame',
      'Cold-Pressed First Extraction Sesame Base',
      'Infused with Sacred Bhimseni Camphor Notes',
    ],
    variants: [
      { id: 'vtt-1l', name: '1 Litre Bottle', unit: '1L', price: 249, originalPrice: 380 },
      { id: 'vtt-5l', name: '5 Litre Temple Can', unit: '5L', price: 1199, originalPrice: 1650 },
      { id: 'vtt-box', name: 'Case of 12 (1L Bottles)', unit: '12L', price: 2799, originalPrice: 3999 },
    ],
    // sankalpOption: true,
  },
  {
    id: 'shri-kesari-dravya-jar',
    name: 'Shri Kesari Yellow Dravya Jars ',
    hindiTitle: 'पीला जार - वंदना दीप द्रव्य',
    category: 'Kesari Deep Dravya',
    price: 299,
    originalPrice: 420,
    rating: 4.95,
    reviewsCount: 980,
    // badge: 'TEMPLE GRADE • AIRTIGHT JAR',
    image: '/images/kesari-jars.png',
    description: 'Consecrated Deep Dravya stored in airtight yellow jars. Emits a warm golden flame with natural aromatic essence, ideal for daily Aarti and Mahadeep worship.',
    features: [
      'Consecrated Yellow Jar Packaging',
      'Radiant Golden Flame & Zero Smoke',
      'Enriched with Sacred Vedic Herbal Extracts',
      'UV-Protected Airtight Preservation',
    ],
    variants: [
      { id: 'skd-500g', name: '500g Airtight Jar', unit: '500g', price: 299, originalPrice: 420 },
      { id: 'skd-1kg', name: '1kg Jumbo Jar', unit: '1kg', price: 549, originalPrice: 799 },
    ],
    // sankalpOption: true,
  },
  {
    id: 'shri-kesari-plus-box',
    name: 'Shri Kesari Plus Gift Boxes ',
    hindiTitle: 'बॉक्स पैक - श्री केसरी प्लस',
    category: 'Curated Ritual Boxes',
    price: 349,
    originalPrice: 499,
    rating: 4.88,
    reviewsCount: 650,
    // badge: 'ROYAL GIFT EDITION',
    image: '/images/kesari-boxes.png',
    description: 'Royal festival box edition containing consecrated Kesari Plus Deep Dravya. Excellent for Diwali gifting, Gruha Pravesh, and corporate temple consignments.',
    features: [
      'Royal Embossed Festival Gift Packaging',
      'Includes Brass Wicks & Consecrated Dravya',
      'Scriptural Purity Certificate Included',
      'Ideal for Deepavali & Gruha Pravesh Gifting',
    ],
    variants: [
      { id: 'skp-single', name: 'Single Royal Box (500g)', unit: '500g', price: 349, originalPrice: 499 },
      { id: 'skp-pair', name: 'Twin Festive Pack (2x 500g)', unit: '1kg', price: 649, originalPrice: 950 },
    ],
    // sankalpOption: true,
  },
 
  {
    id: 'shri-dham-havan-samagri',
    name: 'Shri Dham Havan Samagri',
    hindiTitle: 'शुद्ध सनातनी हवन सामग्री',
    category: 'Hawan Samagri',
    price: 199,
    originalPrice: 299,
    rating: 4.96,
    reviewsCount: 2100,
    // badge: 'PURE SANATANI HAVAN',
    image: '/images/shridham-havan.png',
    description: 'Shri Dham Shudh Sanatani Havan Samagri — a sacred blend of 40+ natural herbs, guggal, dry fruits, kapoor, chandan, and vedic dravya, prepared under the supervision of Vedic Acharyas for Hawan, Yajna & Agnihotra rituals.',
    features: [
      'Blend of 40+ Sacred Vedic Herbs & Dravya',
      'Natural Guggal, Chandan & Kapoor Infused',
      'Prepared Under Vedic Acharya Supervision',
      'Packaged Fresh in Airtight Foil Sachets',
    ],
    variants: [
      { id: 'sdhs-100g', name: '100g Sachet Pack', unit: '100g', price: 199, originalPrice: 299 },
      { id: 'sdhs-500g', name: '500g Bulk Pack', unit: '500g', price: 799, originalPrice: 1199 },
      { id: 'sdhs-1kg', name: '1kg Temple Pack', unit: '1kg', price: 1499, originalPrice: 2199 },
    ],
    // sankalpOption: true,
  },
];

export const PURITY_STANDARDS = [
  {
    title: '100% First Cold-Pressed Sesame Base',
    description: 'Extracted directly from selected black & yellow sesame seeds using traditional wooden ghanis without solvent chemicals or thermal oxidation.',
    standard: 'IS 542:2014 & Scriptural Canons',
    iconName: 'Droplets',
  },
  {
    title: 'Zero Carbon Soot & Non-Blackening Flame',
    description: 'Infused with pure Bhimseni camphor notes that maintain complete combustion, ensuring zero soot marks on temple marble and idols.',
    standard: 'HPLC Tested 99.8% Soot-Free',
    iconName: 'Flame',
  },
  {
    title: 'Airtight UV-Protected Consecrated Jars',
    description: 'Packaged in heavy-gauge leakproof containers under hygienic, consecrated conditions with Gotra Sankalp readiness.',
    standard: 'ISO 22000 & Temple Certified',
    iconName: 'ShieldCheck',
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Mahant Raghav Das Ji',
    author: 'Mahant Raghav Das Ji',
    role: 'Head Priest, Shri Bankey Bihari Temple Complex',
    location: 'Mathura, UP',
    rating: 5,
    comment: 'We have been using Gurukripa Traders Vardaan Til Tail for all our daily Aarti lamps. The flame burns bright, clear, and without a speck of black soot on the temple marble. Truly divine purity.',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 't2',
    name: 'Smt. Sunita Agarwal',
    author: 'Smt. Sunita Agarwal',
    role: 'Devotee, New Delhi',
    location: 'New Delhi',
    rating: 5,
    comment: 'The Shri Kesari Yellow Jars are remarkable! The oil has a soothing sacred scent and burns for hours during Navratri Akhand Jyoti. Packing was airtight and leaked zero drop.',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 't3',
    name: 'Pundit Vishnu Dev Shastri',
    author: 'Pundit Vishnu Dev Shastri',
    role: 'Vedic Ritual Scholar, Varanasi',
    location: 'Varanasi, UP',
    rating: 5,
    comment: 'Their A2 Ghee and Kashmiri Saffron meet every scriptural standard for Mahayagna Abhishek. Highly recommend to all temple trusts and devout families.',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
  },
];
